Add  DevOps team contact in the README
kubesphere-sigs/ks-devops pull request #49
Opened 2021-07-15 00:34 UTC by AbdelouahabMbarki

Added communication channels to the README file
![image](https://user-images.githubusercontent.com/52507296/125709797-fdb717db-6b4a-4dbb-be45-41786fb958a0.png)

2021-07-15 01:24 UTC, LinuxSuRen requested changes
Thanks for helping with this. I found a few places that need to improve.

2021-07-15 01:24 UTC, LinuxSuRen commented on README.md
> +
I prefer to keep these items be closer to each other. Please see the differences below.

![image](https://user-images.githubusercontent.com/1450685/125712604-5b702fef-df05-44bf-811d-d83fe18f082d.png)

![image](https://user-images.githubusercontent.com/1450685/125712626-6b66c919-2812-4c85-9a5c-4d4c3c0192cb.png)

I mean we don't need the extra space here.

2021-07-15 01:24 UTC, LinuxSuRen commented on README.md
> +- [kubesphere Devops google group ](https://groups.google.com/g/kubesphere-sig-devops/)
`kubesphere` -> `KubeSphere`

I prefer to remove the extra space here if you don't have a strong reason for that.

`[kubesphere Devops google group ]` -> `[kubesphere Devops google group]`

2021-07-15 14:29 UTC, AbdelouahabMbarki commented
i added the review changes in the new commit

2021-07-15 15:30 UTC, JohnNiang commented
/lgtm

2021-07-16 01:35 UTC, LinuxSuRen approved these changes
/lgtm

2021-07-16 01:55 UTC, merged