Avoid the error output be hidden
kubesphere-sigs/ks-devops pull request #80
Opened 2021-07-27 09:45 UTC by LinuxSuRen

2021-07-27 10:00 UTC, JohnNiang requested changes

2021-07-27 10:00 UTC, JohnNiang commented on pkg/client/devops/jenkins/build.go
> +	if jobBuild, err = job.getBuildByType(typeStr); err == nil {
Same as above.

2021-07-28 01:06 UTC, LinuxSuRen commented on pkg/client/devops/jenkins/build.go
> +	var job *Job
why?

2021-07-28 01:43 UTC, JohnNiang commented
/lgtm

2021-07-28 01:44 UTC, merged